# Generated by Django 3.2 on 2021-05-18 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfb_app', '0003_gameresults_opponent_army'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresults',
            name='opponent_dw',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_dw', to=settings.AUTH_USER_MODEL),
        ),
    ]
