# Generated by Django 3.2 on 2021-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0004_gameresults_opponent_dw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresults',
            name='opponent',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
