# Generated by Django 3.2.5 on 2021-08-26 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0006_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParingsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('p2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('p3', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('p4', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('p5', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='no_of_players',
            field=models.IntegerField(default=5),
        ),
    ]
