# Generated by Django 3.2.5 on 2021-08-29 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0009_auto_20210829_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='parings_3',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
