# Generated by Django 3.2.5 on 2022-01-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0014_auto_20220105_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_of_3',
            name='date',
        ),
    ]
