# Generated by Django 4.0.3 on 2022-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0017_armys_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_of_3',
            name='p11',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p12',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p13',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p21',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p22',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p23',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p31',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p32',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_3',
            name='p33',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p11',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p12',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p13',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p14',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p21',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p22',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p23',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p24',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p31',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p32',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p33',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p34',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p41',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p42',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p43',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_4',
            name='p44',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p11',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p12',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p13',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p14',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p15',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p21',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p22',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p23',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p24',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p25',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p31',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p32',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p33',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p34',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p35',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p41',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p42',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p43',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p44',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p45',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p51',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p52',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p53',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p54',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='p55',
            field=models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2')]),
        ),
    ]
