# Generated by Django 4.0.3 on 2022-06-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0020_team_of_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_of_5',
            name='op1',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='op2',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='op3',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='op4',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_5',
            name='op5',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op1',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op2',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op3',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op4',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op5',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op6',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op7',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='op8',
            field=models.CharField(choices=[('BH', 'BH'), ('DL', 'DL'), ('DE', 'DE'), ('DH', 'DH'), ('EoS', 'EoS'), ('HE', 'HE'), ('ID', 'ID'), ('KoE', 'KoE'), ('OK', 'OK'), ('OG', 'OG'), ('SA', 'SA'), ('SE', 'SE'), ('UD', 'UD'), ('VC', 'VC'), ('VS', 'VS'), ('WDG', 'WDG')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_of_8',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourney8', to='wfb_app.tournamentetc'),
        ),
    ]
