# Generated by Django 4.0.3 on 2022-07-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0021_alter_team_of_5_op1_alter_team_of_5_op2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parings_3',
        ),
        migrations.DeleteModel(
            name='Parings_4',
        ),
        migrations.DeleteModel(
            name='Parings_5',
        ),
    ]
